FROM python:3.11-slim

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

COPY requirements.frontend.txt .

RUN pip install --no-cache-dir \
    --default-timeout=1200 \
    -r requirements.frontend.txt

COPY app.py /app/app.py
COPY image.png /app/image.png
COPY logo1.png /app/logo1.png
COPY data /app/data

EXPOSE 8501

CMD ["streamlit", "run", "app.py", "--server.address=0.0.0.0", "--server.port=8501"]